name             'wintest'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wintest'
long_description 'Installs/Configures wintest'
version          '0.1.0'
